begin
  foo
rescue Exception => e
  puts e.message
end
